os:
  - linux
  - osx
language: generic
sudo: required
env:
  - DB=postgres
dist: trusty
osx_image: xcode8
addons:
  postgresql: "9.4" # don't need Services when using addons
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - eval "$(curl -sL swift.vapor.sh/ci)"
  - eval "$(curl -sL swift.vapor.sh/codecov)"
