os:
  - linux
  #- osx
language: ruby
sudo: required
dist: trusty
osx_image: xcode8
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - eval "$(curl -sL swift.vapor.sh/ci)"
  - eval "$(curl -sL swift.vapor.sh/codecov)"
