language: generic
matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      env: SCHEME="PostgreSQL"
    - os: osx
      osx_image: xcode9
      env: SCHEME="PostgreSQL-Package"

before_install:
  - brew update
  - gem install xcpretty
  - brew tap vapor/tap
  - brew install vapor

install:
  - rm -rf /usr/local/var/postgres
  - initdb /usr/local/var/postgres -E utf8
  - pg_ctl -D /usr/local/var/postgres start && sleep 3 || true
  - sudo -u travis createuser -s -p 5432 postgres
  - psql -U postgres -c 'create database test;'

script:
  # run unit tests
  - swift build --configuration release
  - swift package generate-xcodeproj
  - xcodebuild -scheme $SCHEME -enableCodeCoverage YES test | xcpretty  # instead of swift test


after_success:
  - bash <(curl -s https://codecov.io/bash)
