os:
  - linux
  #- osx
language: generic
sudo: true
dist: trusty
osx_image: xcode8
addons:
  apt:
    packages:
      - postgresql-9.4
before_install:
     - sudo -u postgres sh -c "createuser -s -p 5432 travis; createdb -O travis -p 5432 travis; createuser -s -p 5433 travis; createdb -O travis -p 5433 travis"
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - eval "$(curl -sL swift.vapor.sh/ci)"
  - eval "$(curl -sL swift.vapor.sh/codecov)"
