os:
  - linux
  #- osx
language: generic
sudo: false
dist: precise
osx_image: xcode8
addons:
  apt:
    packages:
      - clang
      - libicu-dev
      - uuid-dev
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - eval "$(curl -sL swift.vapor.sh/ci)"
  - eval "$(curl -sL swift.vapor.sh/codecov)"
